[tool.poetry]
name = "runner"
version = "0.1.0"
description = ""
authors = ["Piotr Szczechowski <s16096@pjwstk.edu.pl>"]

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
